import { Hero } from './interface';

export var HEROES: Hero[] = [
  { "id": 11, "name": "Mr. Nice" },
  { "id": 12, "name": "Narco" },
  { "id": 13, "name": "Bombasto" },
  { "id": 14, "name": "Celeritas" },
  { "id": 15, "name": "Magneta" },
  { "id": 16, "name": "RubberMan" },
  { "id": 17, "name": "Dynama" },
  { "id": 18, "name": "Dr IQ" },
  { "id": 19, "name": "Magma" },
  { "id": 20, "name": "Tornado" }
];



export var FIELDMETADATA = {
  "fieldmetadata": {
    "country": "IN",
    "data": {
      "stages": [
        {
          "stageName": "Basic Data",
          "stageId": "BD",
          "submitUrl": null,
          "fields": [
            {
              "country": "IN",
              "logical_field_name": "full_name",
              "min_length": "2",
              "status": "A",
              "product_specific": "No",
              "sub_product_code": null,
              "joint": "Y",
              "ntb": "Y",
              "etb": "Y",
              "RTOB_STAGE": "BD",
              "rwb_rtob_stage": "BD",
              "rwb_rtob_sf_stage": null,
              "rwb_category": "bd-1",
              "rwb_ipad": "Y",
              "rwb_desktop": "Y",
              "sc_com": "Y",
              "mobile": "Y",
              "lov_field_name": "Full name",
              "child_lov_field_name": null,
              "rwb_label_name": "Full name",
              "aadhaar_prepop": "Y",
              "etb_preprop": "Y",
              "value_pair": "N",
              "label_length": "9",
              "seq_no": "200",
              "positioning": "1",
              "field_set": "Yes",
              "field_set_name": "Basic Information",
              "component_type": "Text",
              "mandatory": "false",
              "length": "5",
              "type": "Text",
              "lov": "No",
              "regex": "^[a-zA-Z./'&@]+(?: [a-zA-Z./'&@]+)*$",
              "sf": null,
              "sfp": null,
              "prepopulation_service_type": null,
              "prepopulation_field_mapping": null,
              "ui_derivation_logic": null,
              "ui_defaulted_value": null,
              "default_visibility": null,
              "header": null,
              "details": null,
              "max_selects": null,
              "info_tooltips": null,
              "field_set_with_info": null
            },
            {
              "country": "IN",
              "logical_field_name": "title",
              "min_length": null,
              "status": "A",
              "product_specific": "No",
              "sub_product_code": null,
              "joint": "Y",
              "ntb": "Y",
              "etb": "Y",
              "RTOB_STAGE": "BD",
              "rwb_rtob_stage": "BD",
              "rwb_rtob_sf_stage": null,
              "rwb_category": "bd-1",
              "rwb_ipad": "Y",
              "rwb_desktop": "Y",
              "sc_com": "Y",
              "mobile": "Y",
              "lov_field_name": "Title",
              "child_lov_field_name": null,
              "rwb_label_name": "Title",
              "aadhaar_prepop": "N",
              "etb_preprop": "Y",
              "value_pair": "N",
              "label_length": "5",
              "seq_no": "300",
              "positioning": "2",
              "field_set": "Yes",
              "field_set_name": "Basic Information",
              "component_type": "Selection Box",
              "mandatory": "Yes",
              "length": "5",
              "type": "Picklist",
              "lov": "Yes",
              "regex": null,
              "sf": null,
              "sfp": null,
              "prepopulation_service_type": null,
              "prepopulation_field_mapping": null,
              "ui_derivation_logic": null,
              "ui_defaulted_value": null,
              "default_visibility": null,
              "header": null,
              "details": null,
              "max_selects": null,
              "info_tooltips": null,
              "field_set_with_info": null
            },
            {
              "country": "IN",
              "logical_field_name": "first_name",
              "min_length": null,
              "status": "A",
              "product_specific": "No",
              "sub_product_code": null,
              "joint": "Y",
              "ntb": "Y",
              "etb": "Y",
              "RTOB_STAGE": "BD",
              "rwb_rtob_stage": "BD",
              "rwb_rtob_sf_stage": null,
              "rwb_category": "bd-1",
              "rwb_ipad": "Y",
              "rwb_desktop": "Y",
              "sc_com": "Y",
              "mobile": "Y",
              "lov_field_name": "First name",
              "child_lov_field_name": null,
              "rwb_label_name": "First name",
              "aadhaar_prepop": "N",
              "etb_preprop": "Y",
              "value_pair": "N",
              "label_length": "10",
              "seq_no": "400",
              "positioning": "2",
              "field_set": "Yes",
              "field_set_name": "Basic Information",
              "component_type": "Text",
              "mandatory": "true",
              "length": "35",
              "type": "Text",
              "lov": "No",
              "regex": "^[a-zA-Z./'&@]+(?: [a-zA-Z./'&@]+)*$",
              "sf": null,
              "sfp": null,
              "prepopulation_service_type": null,
              "prepopulation_field_mapping": null,
              "ui_derivation_logic": null,
              "ui_defaulted_value": null,
              "default_visibility": null,
              "header": null,
              "details": null,
              "max_selects": null,
              "info_tooltips": null,
              "field_set_with_info": null
            },
            {
              "country": "IN",
              "logical_field_name": "last_name",
              "min_length": null,
              "status": "A",
              "product_specific": "No",
              "sub_product_code": null,
              "joint": "Y",
              "ntb": "Y",
              "etb": "Y",
              "RTOB_STAGE": "BD",
              "rwb_rtob_stage": "BD",
              "rwb_rtob_sf_stage": null,
              "rwb_category": "bd-1",
              "rwb_ipad": "Y",
              "rwb_desktop": "Y",
              "sc_com": "Y",
              "mobile": "Y",
              "lov_field_name": "Last name",
              "child_lov_field_name": null,
              "rwb_label_name": "Last name",
              "aadhaar_prepop": "N",
              "etb_preprop": "Y",
              "value_pair": "N",
              "label_length": "9",
              "seq_no": "600",
              "positioning": "2",
              "field_set": "Yes",
              "field_set_name": "Basic Information",
              "component_type": "Text",
              "mandatory": "false",
              "length": "35",
              "type": "Text",
              "lov": "No",
              "regex": "^[a-zA-Z./'&@]+(?: [a-zA-Z./'&@]+)*$",
              "sf": null,
              "sfp": null,
              "prepopulation_service_type": null,
              "prepopulation_field_mapping": null,
              "ui_derivation_logic": null,
              "ui_defaulted_value": null,
              "default_visibility": null,
              "header": null,
              "details": null,
              "max_selects": null,
              "info_tooltips": null,
              "field_set_with_info": null
            },
            {
              "country": "IN",
              "logical_field_name": "aka_name",
              "min_length": null,
              "status": "A",
              "product_specific": "No",
              "sub_product_code": null,
              "joint": "Y",
              "ntb": "Y",
              "etb": "Y",
              "RTOB_STAGE": "BD",
              "rwb_rtob_stage": "BD",
              "rwb_rtob_sf_stage": null,
              "rwb_category": "bd-1",
              "rwb_ipad": "Y",
              "rwb_desktop": "Y",
              "sc_com": "Y",
              "mobile": "Y",
              "lov_field_name": "Also known as name",
              "child_lov_field_name": null,
              "rwb_label_name": "Also known as name",
              "aadhaar_prepop": "N",
              "etb_preprop": "N",
              "value_pair": "N",
              "label_length": "18",
              "seq_no": "700",
              "positioning": "2",
              "field_set": "Yes",
              "field_set_name": "Basic Information",
              "component_type": "Text",
              "mandatory": "false",
              "length": "110",
              "type": "Text",
              "lov": "No",
              "regex": "^[a-zA-Z/'&@]+(?: [a-zA-Z/'&@]+)*$",
              "sf": null,
              "sfp": null,
              "prepopulation_service_type": null,
              "prepopulation_field_mapping": null,
              "ui_derivation_logic": null,
              "ui_defaulted_value": null,
              "default_visibility": null,
              "header": null,
              "details": null,
              "max_selects": null,
              "info_tooltips": null,
              "field_set_with_info": null
            },
            {
              "country": "IN",
              "logical_field_name": "date_of_birth",
              "min_length": null,
              "status": "A",
              "product_specific": "No",
              "sub_product_code": null,
              "joint": "Y",
              "ntb": "Y",
              "etb": "Y",
              "RTOB_STAGE": "BD",
              "rwb_rtob_stage": "BD",
              "rwb_rtob_sf_stage": null,
              "rwb_category": "bd-1",
              "rwb_ipad": "Y",
              "rwb_desktop": "Y",
              "sc_com": "Y",
              "mobile": "Y",
              "lov_field_name": "Date of birth",
              "child_lov_field_name": null,
              "rwb_label_name": "Date of birth",
              "aadhaar_prepop": "Y",
              "etb_preprop": "Y",
              "value_pair": "N",
              "label_length": "13",
              "seq_no": "900",
              "positioning": "2",
              "field_set": "Yes",
              "field_set_name": "Basic Information",
              "component_type": "Date",
              "mandatory": "true",
              "length": "10",
              "type": "Date",
              "lov": "No",
              "regex": null,
              "sf": null,
              "sfp": null,
              "prepopulation_service_type": null,
              "prepopulation_field_mapping": null,
              "ui_derivation_logic": null,
              "ui_defaulted_value": null,
              "default_visibility": null,
              "header": null,
              "details": null,
              "max_selects": null,
              "info_tooltips": null,
              "field_set_with_info": null
            },
            {
              "country": "IN",
              "logical_field_name": "gender",
              "min_length": null,
              "status": "A",
              "product_specific": "No",
              "sub_product_code": null,
              "joint": "Y",
              "ntb": "Y",
              "etb": "Y",
              "RTOB_STAGE": "BD",
              "rwb_rtob_stage": "BD",
              "rwb_rtob_sf_stage": null,
              "rwb_category": "bd-1",
              "rwb_ipad": "Y",
              "rwb_desktop": "Y",
              "sc_com": "Y",
              "mobile": "Y",
              "lov_field_name": "Gender",
              "child_lov_field_name": null,
              "rwb_label_name": "Gender",
              "aadhaar_prepop": "Y",
              "etb_preprop": "Y",
              "value_pair": "N",
              "label_length": "6",
              "seq_no": "1000",
              "positioning": "2",
              "field_set": "Yes",
              "field_set_name": "Basic Information",
              "component_type": "Selection Box",
              "mandatory": "true",
              "length": "1",
              "type": "Picklist",
              "lov": "Yes",
              "regex": null,
              "sf": null,
              "sfp": null,
              "prepopulation_service_type": null,
              "prepopulation_field_mapping": null,
              "ui_derivation_logic": null,
              "ui_defaulted_value": null,
              "default_visibility": null,
              "header": null,
              "details": null,
              "max_selects": null,
              "info_tooltips": null,
              "field_set_with_info": null
            },
            {
              "country": "IN",
              "logical_field_name": "nationality",
              "min_length": null,
              "status": "A",
              "product_specific": "No",
              "sub_product_code": null,
              "joint": "Y",
              "ntb": "Y",
              "etb": "Y",
              "RTOB_STAGE": "BD",
              "rwb_rtob_stage": "BD",
              "rwb_rtob_sf_stage": null,
              "rwb_category": "bd-1",
              "rwb_ipad": "Y",
              "rwb_desktop": "Y",
              "sc_com": "Y",
              "mobile": "Y",
              "lov_field_name": "Nationality",
              "child_lov_field_name": null,
              "rwb_label_name": "Nationality",
              "aadhaar_prepop": "N",
              "etb_preprop": "Y",
              "value_pair": "N",
              "label_length": "11",
              "seq_no": "1100",
              "positioning": "1",
              "field_set": "Yes",
              "field_set_name": "Basic Information",
              "component_type": "Selection Box",
              "mandatory": "true",
              "length": "3",
              "type": "Picklist",
              "lov": "Yes",
              "regex": null,
              "sf": null,
              "sfp": null,
              "prepopulation_service_type": null,
              "prepopulation_field_mapping": null,
              "ui_derivation_logic": null,
              "ui_defaulted_value": null,
              "default_visibility": null,
              "header": null,
              "details": null,
              "max_selects": "5",
              "info_tooltips": null,
              "field_set_with_info": null
            },
            {
              "country": "IN",
              "logical_field_name": "mobile",
              "min_length": null,
              "status": "A",
              "product_specific": "No",
              "sub_product_code": null,
              "joint": "Y",
              "ntb": "Y",
              "etb": "Y",
              "RTOB_STAGE": "BD",
              "rwb_rtob_stage": "BD",
              "rwb_rtob_sf_stage": null,
              "rwb_category": "bd-1",
              "rwb_ipad": "Y",
              "rwb_desktop": "Y",
              "sc_com": "Y",
              "mobile": "Y",
              "lov_field_name": "Mobile country code",
              "child_lov_field_name": null,
              "rwb_label_name": "Mobile (Country code + Phone No.)",
              "aadhaar_prepop": "N",
              "etb_preprop": "Y",
              "value_pair": "N",
              "label_length": "33",
              "seq_no": "1200",
              "positioning": "2",
              "field_set": "Yes",
              "field_set_name": "Basic Information",
              "component_type": "Number",
              "mandatory": "true",
              "length": "10",
              "type": "Numeric",
              "lov": "Yes",
              "regex": "^[0-9]+$",
              "sf": null,
              "sfp": null,
              "prepopulation_service_type": null,
              "prepopulation_field_mapping": null,
              "ui_derivation_logic": null,
              "ui_defaulted_value": "91",
              "default_visibility": null,
              "header": null,
              "details": null,
              "max_selects": null,
              "info_tooltips": null,
              "field_set_with_info": null
            },
            {
              "country": "IN",
              "logical_field_name": "email",
              "min_length": null,
              "status": "A",
              "product_specific": "No",
              "sub_product_code": null,
              "joint": "Y",
              "ntb": "Y",
              "etb": "Y",
              "RTOB_STAGE": "BD",
              "rwb_rtob_stage": "BD",
              "rwb_rtob_sf_stage": null,
              "rwb_category": "bd-1",
              "rwb_ipad": "Y",
              "rwb_desktop": "Y",
              "sc_com": "Y",
              "mobile": "Y",
              "lov_field_name": "Email",
              "child_lov_field_name": null,
              "rwb_label_name": "Email",
              "aadhaar_prepop": "N",
              "etb_preprop": "Y",
              "value_pair": "N",
              "label_length": "5",
              "seq_no": "1300",
              "positioning": "2",
              "field_set": "Yes",
              "field_set_name": "Basic Information",
              "component_type": "Text",
              "mandatory": "true",
              "length": "150",
              "type": "Text",
              "lov": "No",
              "regex": "(?:[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-zA-Z0-9-]*[a-zA-Z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])",
              "sf": null,
              "sfp": null,
              "prepopulation_service_type": null,
              "prepopulation_field_mapping": null,
              "ui_derivation_logic": null,
              "ui_defaulted_value": null,
              "default_visibility": null,
              "header": null,
              "details": null,
              "max_selects": null,
              "info_tooltips": null,
              "field_set_with_info": null
            },
            {
              "country": "IN",
              "logical_field_name": "aadhaar_no",
              "min_length": "12",
              "status": "A",
              "product_specific": "No",
              "sub_product_code": null,
              "joint": "Y",
              "ntb": "Y",
              "etb": "Y",
              "RTOB_STAGE": "BD",
              "rwb_rtob_stage": "BD",
              "rwb_rtob_sf_stage": null,
              "rwb_category": "bd-1",
              "rwb_ipad": "Y",
              "rwb_desktop": "Y",
              "sc_com": "Y",
              "mobile": "Y",
              "lov_field_name": "Aadhaar No.",
              "child_lov_field_name": null,
              "rwb_label_name": "Aadhaar No.",
              "aadhaar_prepop": "Y",
              "etb_preprop": "Y",
              "value_pair": "N",
              "label_length": "11",
              "seq_no": "1400",
              "positioning": "1",
              "field_set": "Yes",
              "field_set_name": "ID Details",
              "component_type": "Number",
              "mandatory": "false",
              "length": "12",
              "type": "Numeric",
              "lov": "No",
              "regex": "^[0-9]+$",
              "sf": null,
              "sfp": null,
              "prepopulation_service_type": null,
              "prepopulation_field_mapping": null,
              "ui_derivation_logic": null,
              "ui_defaulted_value": null,
              "default_visibility": null,
              "header": null,
              "details": null,
              "max_selects": null,
              "info_tooltips": null,
              "field_set_with_info": null
            },
            {
              "country": "IN",
              "logical_field_name": "pan_no",
              "min_length": "10",
              "status": "A",
              "product_specific": "No",
              "sub_product_code": null,
              "joint": "Y",
              "ntb": "Y",
              "etb": "Y",
              "RTOB_STAGE": "BD",
              "rwb_rtob_stage": "BD",
              "rwb_rtob_sf_stage": null,
              "rwb_category": "bd-1",
              "rwb_ipad": "Y",
              "rwb_desktop": "Y",
              "sc_com": "Y",
              "mobile": "Y",
              "lov_field_name": "PAN No.",
              "child_lov_field_name": null,
              "rwb_label_name": "PAN",
              "aadhaar_prepop": "Y",
              "etb_preprop": "Y",
              "value_pair": "N",
              "label_length": "3",
              "seq_no": "1600",
              "positioning": "2",
              "field_set": "Yes",
              "field_set_name": "ID Details",
              "component_type": "Text",
              "mandatory": "false",
              "length": "10",
              "type": "Text",
              "lov": "No",
              "regex": "^([a-zA-Z]){3}(P|p){1}([a-zA-Z]){1}([0-9]){4}([a-zA-Z]){1}?$",
              "sf": null,
              "sfp": null,
              "prepopulation_service_type": null,
              "prepopulation_field_mapping": null,
              "ui_derivation_logic": null,
              "ui_defaulted_value": null,
              "default_visibility": null,
              "header": null,
              "details": "For instant account set up, your PAN will be required.",
              "max_selects": null,
              "info_tooltips": "Yes",
              "field_set_with_info": null
            }
            // },
            // {
            //   "country": "IN",
            //   "logical_field_name": "other_id_type",
            //   "min_length": null,
            //   "status": "A",
            //   "product_specific": "No",
            //   "sub_product_code": null,
            //   "joint": "Y",
            //   "ntb": "Y",
            //   "etb": "Y",
            //   "RTOB_STAGE": "BD",
            //   "rwb_rtob_stage": "BD",
            //   "rwb_rtob_sf_stage": null,
            //   "rwb_category": "bd-1",
            //   "rwb_ipad": "Y",
            //   "rwb_desktop": "Y",
            //   "sc_com": "Y",
            //   "mobile": "Y",
            //   "lov_field_name": "Other ID type",
            //   "child_lov_field_name": null,
            //   "rwb_label_name": "Additional ID type",
            //   "aadhaar_prepop": "N",
            //   "etb_preprop": "Y",
            //   "value_pair": "N",
            //   "label_length": "18",
            //   "seq_no": "1800",
            //   "positioning": "2",
            //   "field_set": "Yes",
            //   "field_set_name": "ID Details",
            //   "component_type": "Selection Box",
            //   "mandatory": "false",
            //   "length": "3",
            //   "type": "Picklist",
            //   "lov": "Yes",
            //   "regex": null,
            //   "sf": null,
            //   "sfp": null,
            //   "prepopulation_service_type": null,
            //   "prepopulation_field_mapping": null,
            //   "ui_derivation_logic": null,
            //   "ui_defaulted_value": null,
            //   "default_visibility": null,
            //   "header": null,
            //   "details": null,
            //   "max_selects": null,
            //   "info_tooltips": null,
            //   "field_set_with_info": null
            // }
          ]
        }
      ]
    },
    "version": "8.5"
  }
}